apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
  labels:
    cleanup: 'true'
    docker-api-version: '1.39'
    skaffold-builder: local
    skaffold-deployer: kubectl
    skaffold-tag-policy: git-commit
    tail: 'true'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: quickstart-se
      cleanup: 'true'
      docker-api-version: '1.39'
      skaffold-builder: local
      skaffold-deployer: kubectl
      skaffold-tag-policy: git-commit
      tail: 'true'
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quickstart-se
        cleanup: 'true'
        docker-api-version: '1.39'
        skaffold-builder: local
        skaffold-deployer: kubectl
        skaffold-tag-policy: git-commit
        tail: 'true'
        version: v1
    spec:
      containers:
        - image: >-
            phx.ocir.io/oracle-cloudnative/skaffoldrepo/quickstart-se:4bb8f2e-dirty@sha256:aaf42e8b4bc1e10679f36748b53a000ab996360daf4962c1e3e1bf1eae89a344
          imagePullPolicy: IfNotPresent
          name: quickstart-se
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
